# Generated by Django 6.0.6 on 2026-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[(1, 'Literature'), (2, 'Tech'), (3, 'Social')], default=1, max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('slug', models.CharField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
